apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hur36nndr-go 
  janus-idp.io/tekton: hur36nndr-go
  backstage.io/kubernetes-id: hur36nndr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hur36nndr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  